#!/bin/sh

nodes=$1

buildComposeYaml() {
  cat <<HEADER
version: '3'
services:
HEADER
  for i in $(seq "$nodes"); do
    cat <<BLOCK
  node-$i:
    build: ./
    ports:
      - $((5000+i-1)):5000
    environment:
      - EMU_NODES=$nodes
      - EMU_NODE=$i
      - EMU_PORT=5000
      - PYTHONUNBUFFERED=1
BLOCK
  done
}

buildComposeYaml

buildComposeYaml | docker-compose -f- up --build
